# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/minitest-rails/all/minitest-rails.rbi
#
# minitest-rails-6.1.0

module Minitest
end
module Minitest::Rails
end
class Minitest::Rails::Railtie < Rails::Railtie
end
