# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/omniauth-salesforce/all/omniauth-salesforce.rbi
#
# omniauth-salesforce-1.0.5

module OmniAuth
end
module OmniAuth::Salesforce
end
module OmniAuth::Strategies
end
class OmniAuth::Strategies::Salesforce < OmniAuth::Strategies::OAuth2
  def auth_hash; end
  def raw_info; end
  def request_phase; end
  extend OmniAuth::Strategy::ClassMethods
end
class OmniAuth::Strategies::SalesforceSandbox < OmniAuth::Strategies::Salesforce
  extend OmniAuth::Strategy::ClassMethods
end
class OmniAuth::Strategies::DatabaseDotCom < OmniAuth::Strategies::Salesforce
  extend OmniAuth::Strategy::ClassMethods
end
class OmniAuth::Strategies::SalesforcePreRelease < OmniAuth::Strategies::Salesforce
  extend OmniAuth::Strategy::ClassMethods
end
