# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/resque-heroku-signals/all/resque-heroku-signals.rbi
#
# resque-heroku-signals-2.1.0

module Resque
  def self.heroku_will_terminate?; end
end
