# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/ruby2_keywords/all/ruby2_keywords.rbi
#
# ruby2_keywords-0.0.5

class Module
  def ruby2_keywords(name, *arg1); end
end
class Proc
  def ruby2_keywords; end
end
class Hash
  def self.ruby2_keywords_hash(hash); end
  def self.ruby2_keywords_hash?(hash); end
end
