# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/sentry-resque/all/sentry-resque.rbi
#
# sentry-resque-4.7.3

module Sentry
end
class Sentry::Configuration
  def resque; end
end
module Sentry::Resque
  def finish_transaction(transaction, status); end
  def generate_contexts; end
  def perform; end
  extend Sentry::Integrable
end
class Sentry::Resque::Configuration
  def initialize; end
  def report_after_job_retries; end
  def report_after_job_retries=(arg0); end
end
class Sentry::Resque::Railtie < Rails::Railtie
end
