# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/unf/all/unf.rbi
#
# unf-0.1.4

module UNF
end
class String
  def to_nfc; end
  def to_nfd; end
  def to_nfkc; end
  def to_nfkd; end
end
