//
//
// File generated from our OpenAPI spec
//
//

package stripe

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/stripe/stripe-go/v86/form"
)

// v1InvoiceRenderingTemplateService is used to invoke /v1/invoice_rendering_templates APIs.
type v1InvoiceRenderingTemplateService struct {
	B   Backend
	Key string
}

// Retrieves an invoice rendering template with the given ID. It by default returns the latest version of the template. Optionally, specify a version to see previous versions.
func (c v1InvoiceRenderingTemplateService) Retrieve(ctx context.Context, id string, params *InvoiceRenderingTemplateRetrieveParams) (*InvoiceRenderingTemplate, error) {
	if params == nil {
		params = &InvoiceRenderingTemplateRetrieveParams{}
	}
	params.Context = ctx
	path := FormatURLPath("/v1/invoice_rendering_templates/%s", id)
	invoicerenderingtemplate := &InvoiceRenderingTemplate{}
	err := c.B.Call(http.MethodGet, path, c.Key, params, invoicerenderingtemplate)
	return invoicerenderingtemplate, err
}

// Updates the status of an invoice rendering template to ‘archived' so no new Stripe objects (customers, invoices, etc.) can reference it. The template can also no longer be updated. However, if the template is already set on a Stripe object, it will continue to be applied on invoices generated by it.
func (c v1InvoiceRenderingTemplateService) Archive(ctx context.Context, id string, params *InvoiceRenderingTemplateArchiveParams) (*InvoiceRenderingTemplate, error) {
	if params == nil {
		params = &InvoiceRenderingTemplateArchiveParams{}
	}
	params.Context = ctx
	path := FormatURLPath("/v1/invoice_rendering_templates/%s/archive", id)
	invoicerenderingtemplate := &InvoiceRenderingTemplate{}
	err := c.B.Call(
		http.MethodPost, path, c.Key, params, invoicerenderingtemplate)
	return invoicerenderingtemplate, err
}

// Serializes an InvoiceRenderingTemplate archive request into a batch job JSONL line.
func (c v1InvoiceRenderingTemplateService) MarshalBatchArchive(id string, params *InvoiceRenderingTemplateArchiveParams) (string, error) {
	itemID, err := newUUID4()
	if err != nil {
		return "", err
	}

	item := struct {
		ID            string            `json:"id"`
		Context       string            `json:"context,omitempty"`
		StripeVersion string            `json:"stripe_version,omitempty"`
		PathParams    map[string]string `json:"path_params,omitempty"`
		Params        interface{}       `json:"params"`
	}{
		ID:            itemID,
		PathParams:    map[string]string{"template": id},
		StripeVersion: APIVersion,
	}
	if params != nil {
		item.Params = params
		if params.StripeContext != nil {
			item.Context = *params.StripeContext
		}
	}
	b, err := json.Marshal(item)
	if err != nil {
		return "", err
	}
	return string(b), nil
}

// Serializes an InvoiceRenderingTemplate unarchive request into a batch job JSONL line.
func (c v1InvoiceRenderingTemplateService) MarshalBatchUnarchive(id string, params *InvoiceRenderingTemplateUnarchiveParams) (string, error) {
	itemID, err := newUUID4()
	if err != nil {
		return "", err
	}

	item := struct {
		ID            string            `json:"id"`
		Context       string            `json:"context,omitempty"`
		StripeVersion string            `json:"stripe_version,omitempty"`
		PathParams    map[string]string `json:"path_params,omitempty"`
		Params        interface{}       `json:"params"`
	}{
		ID:            itemID,
		PathParams:    map[string]string{"template": id},
		StripeVersion: APIVersion,
	}
	if params != nil {
		item.Params = params
		if params.StripeContext != nil {
			item.Context = *params.StripeContext
		}
	}
	b, err := json.Marshal(item)
	if err != nil {
		return "", err
	}
	return string(b), nil
}

// Unarchive an invoice rendering template so it can be used on new Stripe objects again.
func (c v1InvoiceRenderingTemplateService) Unarchive(ctx context.Context, id string, params *InvoiceRenderingTemplateUnarchiveParams) (*InvoiceRenderingTemplate, error) {
	if params == nil {
		params = &InvoiceRenderingTemplateUnarchiveParams{}
	}
	params.Context = ctx
	path := FormatURLPath("/v1/invoice_rendering_templates/%s/unarchive", id)
	invoicerenderingtemplate := &InvoiceRenderingTemplate{}
	err := c.B.Call(
		http.MethodPost, path, c.Key, params, invoicerenderingtemplate)
	return invoicerenderingtemplate, err
}

// List all templates, ordered by creation date, with the most recently created template appearing first.
func (c v1InvoiceRenderingTemplateService) List(ctx context.Context, listParams *InvoiceRenderingTemplateListParams) *V1List[*InvoiceRenderingTemplate] {
	if listParams == nil {
		listParams = &InvoiceRenderingTemplateListParams{}
	}
	listParams.Context = ctx
	return newV1List(ctx, listParams, func(ctx context.Context, p *Params, b *form.Values) (*v1Page[*InvoiceRenderingTemplate], error) {
		list := &v1Page[*InvoiceRenderingTemplate]{}
		if p == nil {
			p = &Params{}
		}
		p.Context = ctx
		err := c.B.CallRaw(http.MethodGet, "/v1/invoice_rendering_templates", c.Key, []byte(b.Encode()), p, list)
		return list, err
	})
}
