//
//
// File generated from our OpenAPI spec
//
//

package stripe

import (
	"encoding/json"
	"github.com/stripe/stripe-go/v85/form"
)

// The type of the product. The product is either of type `good`, which is eligible for use with Orders and SKUs, or `service`, which is eligible for use with Subscriptions and Plans.
type ProductType string

// List of values that ProductType can take
const (
	ProductTypeGood    ProductType = "good"
	ProductTypeService ProductType = "service"
)

// Delete a product. Deleting a product is only possible if it has no prices associated with it. Additionally, deleting a product with type=good is only possible if it has no SKUs associated with it.
type ProductParams struct {
	Params `form:"*"`
	// Whether the product is currently available for purchase. Defaults to `true`.
	Active *bool `form:"active" json:"active,omitempty"`
	// The ID of the [Price](https://docs.stripe.com/api/prices) object that is the default price for this product.
	DefaultPrice *string `form:"default_price" json:"default_price,omitempty"`
	// Data used to generate a new [Price](https://docs.stripe.com/api/prices) object. This Price will be set as the default price for this product.
	DefaultPriceData *ProductDefaultPriceDataParams `form:"default_price_data" json:"default_price_data,omitempty"`
	// The product's description, meant to be displayable to the customer. Use this field to optionally store a long form explanation of the product being sold for your own rendering purposes.
	Description *string `form:"description" json:"description,omitempty"`
	// Specifies which fields in the response should be expanded.
	Expand []*string `form:"expand" json:"expand,omitempty"`
	// An identifier will be randomly generated by Stripe. You can optionally override this ID, but the ID must be unique across all products in your Stripe account.
	ID *string `form:"id" json:"id,omitempty"`
	// Other identifiers for this product.
	Identifiers *ProductIdentifiersParams `form:"identifiers" json:"identifiers,omitempty"`
	// A list of up to 8 URLs of images for this product, meant to be displayable to the customer.
	Images []*string `form:"images" json:"images,omitempty"`
	// A list of up to 15 marketing features for this product. These are displayed in [pricing tables](https://docs.stripe.com/payments/checkout/pricing-table).
	MarketingFeatures []*ProductMarketingFeatureParams `form:"marketing_features" json:"marketing_features,omitempty"`
	// Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
	Metadata map[string]string `form:"metadata" json:"metadata,omitempty"`
	// The product's name, meant to be displayable to the customer.
	Name *string `form:"name" json:"name,omitempty"`
	// The dimensions of this product for shipping purposes.
	PackageDimensions *ProductPackageDimensionsParams `form:"package_dimensions" json:"package_dimensions,omitempty"`
	// Whether this product is shipped (i.e., physical goods).
	Shippable *bool `form:"shippable" json:"shippable,omitempty"`
	// An arbitrary string to be displayed on your customer's credit card or bank statement. While most banks display this information consistently, some may display it incorrectly or not at all.
	//
	// This may be up to 22 characters. The statement description may not include `<`, `>`, `\`, `"`, `'` characters, and will appear on your customer's statement in capital letters. Non-ASCII characters are automatically stripped.
	//  It must contain at least one letter. May only be set if `type=service`. Only used for subscription payments.
	StatementDescriptor *string `form:"statement_descriptor" json:"statement_descriptor,omitempty"`
	// A [tax code](https://docs.stripe.com/tax/tax-categories) ID.
	TaxCode *string `form:"tax_code" json:"tax_code,omitempty"`
	// Tax details for this product, including the [tax code](https://docs.stripe.com/tax/tax-codes) and an optional performance location.
	TaxDetails *ProductTaxDetailsParams `form:"tax_details" json:"tax_details,omitempty"`
	// The type of the product. Defaults to `service` if not explicitly specified, enabling use of this product with Subscriptions and Plans. Set this parameter to `good` to use this product with Orders and SKUs. On API versions before `2018-02-05`, this field defaults to `good` for compatibility reasons.
	Type *string `form:"type" json:"type,omitempty"`
	// A label that represents units of this product. When set, this will be included in customers' receipts, invoices, Checkout, and the customer portal. May only be set if `type=service`.
	UnitLabel *string `form:"unit_label" json:"unit_label,omitempty"`
	// A URL of a publicly-accessible webpage for this product.
	URL         *string                   `form:"url" json:"url,omitempty"`
	UnsetFields []ProductParamsUnsetField `form:"-" json:"-"`
}

// ProductParamsUnsetField is the list of fields that can be cleared/unset on ProductParams.
type ProductParamsUnsetField string

const (
	ProductParamsUnsetFieldDescription       ProductParamsUnsetField = "description"
	ProductParamsUnsetFieldImages            ProductParamsUnsetField = "images"
	ProductParamsUnsetFieldMarketingFeatures ProductParamsUnsetField = "marketing_features"
	ProductParamsUnsetFieldMetadata          ProductParamsUnsetField = "metadata"
	ProductParamsUnsetFieldPackageDimensions ProductParamsUnsetField = "package_dimensions"
	ProductParamsUnsetFieldTaxCode           ProductParamsUnsetField = "tax_code"
	ProductParamsUnsetFieldTaxDetails        ProductParamsUnsetField = "tax_details"
	ProductParamsUnsetFieldUnitLabel         ProductParamsUnsetField = "unit_label"
	ProductParamsUnsetFieldURL               ProductParamsUnsetField = "url"
)

// AddUnsetField adds a field to the list of fields to clear/unset on this params object.
func (p *ProductParams) AddUnsetField(field ProductParamsUnsetField) {
	p.UnsetFields = append(p.UnsetFields, field)
}

// AddExpand appends a new field to expand.
func (p *ProductParams) AddExpand(f string) {
	p.Expand = append(p.Expand, &f)
}

// AddMetadata adds a new key-value pair to the Metadata.
func (p *ProductParams) AddMetadata(key string, value string) {
	if p.Metadata == nil {
		p.Metadata = make(map[string]string)
	}

	p.Metadata[key] = value
}

// Other identifiers for this product.
type ProductIdentifiersParams struct {
	// European Article Number (EAN) consisting of 8 or 13 digits and optional dashes. You may optionally provide a leading 0 for a total of 14 digits. The final digit is a validated check digit.
	Ean *string `form:"ean" json:"ean,omitempty"`
	// Global Trade Item Number (GTIN) consisting of 8, 12, 13, or 14 digits and optional dashes. The final digit is a validated check digit.
	Gtin *string `form:"gtin" json:"gtin,omitempty"`
	// International Standard Book Number (ISBN) consisting of 10 or 13 digits and optional dashes. The final digit is a validated check digit. For ISBN-10, the final digit may be a `X`.
	Isbn *string `form:"isbn" json:"isbn,omitempty"`
	// Japanese Article Number (JAN) consisting of 13 digits and optional dashes. The first two digits must either be `45` or `49`. The final digit is a validated check digit.
	Jan *string `form:"jan" json:"jan,omitempty"`
	// Manufacturer Part Number (MPN). May include up to 70 alphanumeric characters and dashes.
	Mpn *string `form:"mpn" json:"mpn,omitempty"`
	// National Stock Number (NSN) consisting of 13 digits and optional dashes. The seventh character may also be alphanumeric.
	Nsn *string `form:"nsn" json:"nsn,omitempty"`
	// Universal Product Code (UPC) consisting of 12 digits and optional dashes. The final digit is a validated check digit.
	Upc         *string                              `form:"upc" json:"upc,omitempty"`
	UnsetFields []ProductIdentifiersParamsUnsetField `form:"-" json:"-"`
}

// ProductIdentifiersParamsUnsetField is the list of fields that can be cleared/unset on ProductIdentifiersParams.
type ProductIdentifiersParamsUnsetField string

const (
	ProductIdentifiersParamsUnsetFieldEan  ProductIdentifiersParamsUnsetField = "ean"
	ProductIdentifiersParamsUnsetFieldGtin ProductIdentifiersParamsUnsetField = "gtin"
	ProductIdentifiersParamsUnsetFieldIsbn ProductIdentifiersParamsUnsetField = "isbn"
	ProductIdentifiersParamsUnsetFieldJan  ProductIdentifiersParamsUnsetField = "jan"
	ProductIdentifiersParamsUnsetFieldMpn  ProductIdentifiersParamsUnsetField = "mpn"
	ProductIdentifiersParamsUnsetFieldNsn  ProductIdentifiersParamsUnsetField = "nsn"
	ProductIdentifiersParamsUnsetFieldUpc  ProductIdentifiersParamsUnsetField = "upc"
)

// AddUnsetField adds a field to the list of fields to clear/unset on this params object.
func (p *ProductIdentifiersParams) AddUnsetField(field ProductIdentifiersParamsUnsetField) {
	p.UnsetFields = append(p.UnsetFields, field)
}

// A list of up to 15 marketing features for this product. These are displayed in [pricing tables](https://docs.stripe.com/payments/checkout/pricing-table).
type ProductMarketingFeatureParams struct {
	// The marketing feature name. Up to 80 characters long.
	Name *string `form:"name" json:"name"`
}

// The dimensions of this product for shipping purposes.
type ProductPackageDimensionsParams struct {
	// Height, in inches. Maximum precision is 2 decimal places.
	Height *float64 `form:"height" json:"height"`
	// Length, in inches. Maximum precision is 2 decimal places.
	Length *float64 `form:"length" json:"length"`
	// Weight, in ounces. Maximum precision is 2 decimal places.
	Weight *float64 `form:"weight" json:"weight"`
	// Width, in inches. Maximum precision is 2 decimal places.
	Width *float64 `form:"width" json:"width"`
}

// Tax details for this product, including the [tax code](https://docs.stripe.com/tax/tax-codes) and an optional performance location.
type ProductTaxDetailsParams struct {
	// A tax location ID. Depending on the [tax code](https://docs.stripe.com/tax/tax-for-tickets/reference/tax-location-performance), this is required, optional, or not supported.
	PerformanceLocation *string `form:"performance_location" json:"performance_location,omitempty"`
	// A [tax code](https://docs.stripe.com/tax/tax-categories) ID.
	TaxCode     *string                             `form:"tax_code" json:"tax_code,omitempty"`
	UnsetFields []ProductTaxDetailsParamsUnsetField `form:"-" json:"-"`
}

// ProductTaxDetailsParamsUnsetField is the list of fields that can be cleared/unset on ProductTaxDetailsParams.
type ProductTaxDetailsParamsUnsetField string

const (
	ProductTaxDetailsParamsUnsetFieldTaxCode ProductTaxDetailsParamsUnsetField = "tax_code"
)

// AddUnsetField adds a field to the list of fields to clear/unset on this params object.
func (p *ProductTaxDetailsParams) AddUnsetField(field ProductTaxDetailsParamsUnsetField) {
	p.UnsetFields = append(p.UnsetFields, field)
}

// Returns a list of your products. The products are returned sorted by creation date, with the most recently created products appearing first.
type ProductListParams struct {
	ListParams `form:"*"`
	// Only return products that are active or inactive (e.g., pass `false` to list all inactive products).
	Active *bool `form:"active" json:"active,omitempty"`
	// Only return products that were created during the given date interval.
	Created *int64 `form:"created" json:"created,omitempty"`
	// Only return products that were created during the given date interval.
	CreatedRange *RangeQueryParams `form:"created" json:"-"`
	// Specifies which fields in the response should be expanded.
	Expand []*string `form:"expand" json:"expand,omitempty"`
	// Only return products with the given IDs. Cannot be used with [starting_after](https://api.stripe.com#list_products-starting_after) or [ending_before](https://api.stripe.com#list_products-ending_before).
	IDs []*string `form:"ids" json:"ids,omitempty"`
	// Only return products that can be shipped (i.e., physical, not digital products).
	Shippable *bool `form:"shippable" json:"shippable,omitempty"`
	// Only return products of this type.
	Type *string `form:"type" json:"type,omitempty"`
	// Only return products with the given url.
	URL *string `form:"url" json:"url,omitempty"`
}

// AddExpand appends a new field to expand.
func (p *ProductListParams) AddExpand(f string) {
	p.Expand = append(p.Expand, &f)
}

// When set, provides configuration for the amount to be adjusted by the customer during Checkout Sessions and Payment Links.
type ProductDefaultPriceDataCurrencyOptionsCustomUnitAmountParams struct {
	// Pass in `true` to enable `custom_unit_amount`, otherwise omit `custom_unit_amount`.
	Enabled *bool `form:"enabled" json:"enabled"`
	// The maximum unit amount the customer can specify for this item.
	Maximum *int64 `form:"maximum" json:"maximum,omitempty"`
	// The minimum unit amount the customer can specify for this item. Must be at least the minimum charge amount.
	Minimum *int64 `form:"minimum" json:"minimum,omitempty"`
	// The starting unit amount which can be updated by the customer.
	Preset *int64 `form:"preset" json:"preset,omitempty"`
}

// Each element represents a pricing tier. This parameter requires `billing_scheme` to be set to `tiered`. See also the documentation for `billing_scheme`.
type ProductDefaultPriceDataCurrencyOptionsTierParams struct {
	// The flat billing amount for an entire tier, regardless of the number of units in the tier.
	FlatAmount *int64 `form:"flat_amount" json:"flat_amount,omitempty"`
	// Same as `flat_amount`, but accepts a decimal value representing an integer in the minor units of the currency. Only one of `flat_amount` and `flat_amount_decimal` can be set.
	FlatAmountDecimal *float64 `form:"flat_amount_decimal,high_precision" json:"flat_amount_decimal,string,omitempty"`
	// The per unit billing amount for each individual unit for which this tier applies.
	UnitAmount *int64 `form:"unit_amount" json:"unit_amount,omitempty"`
	// Same as `unit_amount`, but accepts a decimal value in cents (or local equivalent) with at most 12 decimal places. Only one of `unit_amount` and `unit_amount_decimal` can be set.
	UnitAmountDecimal *float64 `form:"unit_amount_decimal,high_precision" json:"unit_amount_decimal,string,omitempty"`
	// Specifies the upper bound of this tier. The lower bound of a tier is the upper bound of the previous tier adding one. Use `inf` to define a fallback tier.
	UpTo    *int64 `form:"up_to" json:"up_to"`
	UpToInf *bool  `form:"-"` // See custom AppendTo
}

// AppendTo implements custom encoding logic for ProductDefaultPriceDataCurrencyOptionsTierParams.
func (p *ProductDefaultPriceDataCurrencyOptionsTierParams) AppendTo(body *form.Values, keyParts []string) {
	if BoolValue(p.UpToInf) {
		body.Add(form.FormatKey(append(keyParts, "up_to")), "inf")
	}
}

// Prices defined in each available currency option. Each key must be a three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html) and a [supported currency](https://stripe.com/docs/currencies).
type ProductDefaultPriceDataCurrencyOptionsParams struct {
	// When set, provides configuration for the amount to be adjusted by the customer during Checkout Sessions and Payment Links.
	CustomUnitAmount *ProductDefaultPriceDataCurrencyOptionsCustomUnitAmountParams `form:"custom_unit_amount" json:"custom_unit_amount,omitempty"`
	// Only required if a [default tax behavior](https://docs.stripe.com/tax/products-prices-tax-categories-tax-behavior#setting-a-default-tax-behavior-(recommended)) was not provided in the Stripe Tax settings. Specifies whether the price is considered inclusive of taxes or exclusive of taxes. One of `inclusive`, `exclusive`, or `unspecified`. Once specified as either `inclusive` or `exclusive`, it cannot be changed.
	TaxBehavior *string `form:"tax_behavior" json:"tax_behavior,omitempty"`
	// Each element represents a pricing tier. This parameter requires `billing_scheme` to be set to `tiered`. See also the documentation for `billing_scheme`.
	Tiers []*ProductDefaultPriceDataCurrencyOptionsTierParams `form:"tiers" json:"tiers,omitempty"`
	// A positive integer in cents (or local equivalent) (or 0 for a free price) representing how much to charge.
	UnitAmount *int64 `form:"unit_amount" json:"unit_amount,omitempty"`
	// Same as `unit_amount`, but accepts a decimal value in cents (or local equivalent) with at most 12 decimal places. Only one of `unit_amount` and `unit_amount_decimal` can be set.
	UnitAmountDecimal *float64 `form:"unit_amount_decimal,high_precision" json:"unit_amount_decimal,string,omitempty"`
}

// When set, provides configuration for the amount to be adjusted by the customer during Checkout Sessions and Payment Links.
type ProductDefaultPriceDataCustomUnitAmountParams struct {
	// Pass in `true` to enable `custom_unit_amount`, otherwise omit `custom_unit_amount`.
	Enabled *bool `form:"enabled" json:"enabled"`
	// The maximum unit amount the customer can specify for this item.
	Maximum *int64 `form:"maximum" json:"maximum,omitempty"`
	// The minimum unit amount the customer can specify for this item. Must be at least the minimum charge amount.
	Minimum *int64 `form:"minimum" json:"minimum,omitempty"`
	// The starting unit amount which can be updated by the customer.
	Preset *int64 `form:"preset" json:"preset,omitempty"`
}

// The recurring components of a price such as `interval` and `interval_count`.
type ProductDefaultPriceDataRecurringParams struct {
	// Specifies billing frequency. Either `day`, `week`, `month` or `year`.
	Interval *string `form:"interval" json:"interval"`
	// The number of intervals between subscription billings. For example, `interval=month` and `interval_count=3` bills every 3 months. Maximum of three years interval allowed (3 years, 36 months, or 156 weeks).
	IntervalCount *int64 `form:"interval_count" json:"interval_count,omitempty"`
}

// Data used to generate a new [Price](https://docs.stripe.com/api/prices) object. This Price will be set as the default price for this product.
type ProductDefaultPriceDataParams struct {
	// Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
	Currency *string `form:"currency" json:"currency"`
	// Prices defined in each available currency option. Each key must be a three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html) and a [supported currency](https://stripe.com/docs/currencies).
	CurrencyOptions map[string]*ProductDefaultPriceDataCurrencyOptionsParams `form:"currency_options" json:"currency_options,omitempty"`
	// When set, provides configuration for the amount to be adjusted by the customer during Checkout Sessions and Payment Links.
	CustomUnitAmount *ProductDefaultPriceDataCustomUnitAmountParams `form:"custom_unit_amount" json:"custom_unit_amount,omitempty"`
	// Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
	Metadata map[string]string `form:"metadata" json:"metadata,omitempty"`
	// The recurring components of a price such as `interval` and `interval_count`.
	Recurring *ProductDefaultPriceDataRecurringParams `form:"recurring" json:"recurring,omitempty"`
	// Only required if a [default tax behavior](https://docs.stripe.com/tax/products-prices-tax-categories-tax-behavior#setting-a-default-tax-behavior-(recommended)) was not provided in the Stripe Tax settings. Specifies whether the price is considered inclusive of taxes or exclusive of taxes. One of `inclusive`, `exclusive`, or `unspecified`. Once specified as either `inclusive` or `exclusive`, it cannot be changed.
	TaxBehavior *string `form:"tax_behavior" json:"tax_behavior,omitempty"`
	// A positive integer in cents (or local equivalent) (or 0 for a free price) representing how much to charge. One of `unit_amount`, `unit_amount_decimal`, or `custom_unit_amount` is required.
	UnitAmount *int64 `form:"unit_amount" json:"unit_amount,omitempty"`
	// Same as `unit_amount`, but accepts a decimal value in cents (or local equivalent) with at most 12 decimal places. Only one of `unit_amount` and `unit_amount_decimal` can be set.
	UnitAmountDecimal *float64 `form:"unit_amount_decimal,high_precision" json:"unit_amount_decimal,string,omitempty"`
}

// AddMetadata adds a new key-value pair to the Metadata.
func (p *ProductDefaultPriceDataParams) AddMetadata(key string, value string) {
	if p.Metadata == nil {
		p.Metadata = make(map[string]string)
	}

	p.Metadata[key] = value
}

// Search for products you've previously created using Stripe's [Search Query Language](https://docs.stripe.com/docs/search#search-query-language).
// Don't use search in read-after-write flows where strict consistency is necessary. Under normal operating
// conditions, data is searchable in less than a minute. Occasionally, propagation of new or updated data can be up
// to an hour behind during outages. Search functionality is not available to merchants in India.
type ProductSearchParams struct {
	SearchParams `form:"*"`
	// Specifies which fields in the response should be expanded.
	Expand []*string `form:"expand" json:"expand,omitempty"`
	// A cursor for pagination across multiple pages of results. Don't include this parameter on the first call. Use the next_page value returned in a previous response to request subsequent results.
	Page *string `form:"page" json:"page,omitempty"`
}

// AddExpand appends a new field to expand.
func (p *ProductSearchParams) AddExpand(f string) {
	p.Expand = append(p.Expand, &f)
}

// Delete a product. Deleting a product is only possible if it has no prices associated with it. Additionally, deleting a product with type=good is only possible if it has no SKUs associated with it.
type ProductDeleteParams struct {
	Params `form:"*"`
}

// Retrieves the details of an existing product. Supply the unique product ID from either a product creation request or the product list, and Stripe will return the corresponding product information.
type ProductRetrieveParams struct {
	Params `form:"*"`
	// Specifies which fields in the response should be expanded.
	Expand []*string `form:"expand" json:"expand,omitempty"`
}

// AddExpand appends a new field to expand.
func (p *ProductRetrieveParams) AddExpand(f string) {
	p.Expand = append(p.Expand, &f)
}

// Other identifiers for this product.
type ProductUpdateIdentifiersParams struct {
	// European Article Number (EAN) consisting of 8 or 13 digits and optional dashes. You may optionally provide a leading 0 for a total of 14 digits. The final digit is a validated check digit.
	Ean *string `form:"ean" json:"ean,omitempty"`
	// Global Trade Item Number (GTIN) consisting of 8, 12, 13, or 14 digits and optional dashes. The final digit is a validated check digit.
	Gtin *string `form:"gtin" json:"gtin,omitempty"`
	// International Standard Book Number (ISBN) consisting of 10 or 13 digits and optional dashes. The final digit is a validated check digit. For ISBN-10, the final digit may be a `X`.
	Isbn *string `form:"isbn" json:"isbn,omitempty"`
	// Japanese Article Number (JAN) consisting of 13 digits and optional dashes. The first two digits must either be `45` or `49`. The final digit is a validated check digit.
	Jan *string `form:"jan" json:"jan,omitempty"`
	// Manufacturer Part Number (MPN). May include up to 70 alphanumeric characters and dashes.
	Mpn *string `form:"mpn" json:"mpn,omitempty"`
	// National Stock Number (NSN) consisting of 13 digits and optional dashes. The seventh character may also be alphanumeric.
	Nsn *string `form:"nsn" json:"nsn,omitempty"`
	// Universal Product Code (UPC) consisting of 12 digits and optional dashes. The final digit is a validated check digit.
	Upc         *string                                    `form:"upc" json:"upc,omitempty"`
	UnsetFields []ProductUpdateIdentifiersParamsUnsetField `form:"-" json:"-"`
}

// ProductUpdateIdentifiersParamsUnsetField is the list of fields that can be cleared/unset on ProductUpdateIdentifiersParams.
type ProductUpdateIdentifiersParamsUnsetField string

const (
	ProductUpdateIdentifiersParamsUnsetFieldEan  ProductUpdateIdentifiersParamsUnsetField = "ean"
	ProductUpdateIdentifiersParamsUnsetFieldGtin ProductUpdateIdentifiersParamsUnsetField = "gtin"
	ProductUpdateIdentifiersParamsUnsetFieldIsbn ProductUpdateIdentifiersParamsUnsetField = "isbn"
	ProductUpdateIdentifiersParamsUnsetFieldJan  ProductUpdateIdentifiersParamsUnsetField = "jan"
	ProductUpdateIdentifiersParamsUnsetFieldMpn  ProductUpdateIdentifiersParamsUnsetField = "mpn"
	ProductUpdateIdentifiersParamsUnsetFieldNsn  ProductUpdateIdentifiersParamsUnsetField = "nsn"
	ProductUpdateIdentifiersParamsUnsetFieldUpc  ProductUpdateIdentifiersParamsUnsetField = "upc"
)

// AddUnsetField adds a field to the list of fields to clear/unset on this params object.
func (p *ProductUpdateIdentifiersParams) AddUnsetField(field ProductUpdateIdentifiersParamsUnsetField) {
	p.UnsetFields = append(p.UnsetFields, field)
}

// A list of up to 15 marketing features for this product. These are displayed in [pricing tables](https://docs.stripe.com/payments/checkout/pricing-table).
type ProductUpdateMarketingFeatureParams struct {
	// The marketing feature name. Up to 80 characters long.
	Name *string `form:"name" json:"name"`
}

// The dimensions of this product for shipping purposes.
type ProductUpdatePackageDimensionsParams struct {
	// Height, in inches. Maximum precision is 2 decimal places.
	Height *float64 `form:"height" json:"height"`
	// Length, in inches. Maximum precision is 2 decimal places.
	Length *float64 `form:"length" json:"length"`
	// Weight, in ounces. Maximum precision is 2 decimal places.
	Weight *float64 `form:"weight" json:"weight"`
	// Width, in inches. Maximum precision is 2 decimal places.
	Width *float64 `form:"width" json:"width"`
}

// Tax details for this product, including the [tax code](https://docs.stripe.com/tax/tax-codes) and an optional performance location.
type ProductUpdateTaxDetailsParams struct {
	// A tax location ID. Depending on the [tax code](https://docs.stripe.com/tax/tax-for-tickets/reference/tax-location-performance), this is required, optional, or not supported.
	PerformanceLocation *string `form:"performance_location" json:"performance_location,omitempty"`
	// A [tax code](https://docs.stripe.com/tax/tax-categories) ID.
	TaxCode     *string                                   `form:"tax_code" json:"tax_code,omitempty"`
	UnsetFields []ProductUpdateTaxDetailsParamsUnsetField `form:"-" json:"-"`
}

// ProductUpdateTaxDetailsParamsUnsetField is the list of fields that can be cleared/unset on ProductUpdateTaxDetailsParams.
type ProductUpdateTaxDetailsParamsUnsetField string

const (
	ProductUpdateTaxDetailsParamsUnsetFieldTaxCode ProductUpdateTaxDetailsParamsUnsetField = "tax_code"
)

// AddUnsetField adds a field to the list of fields to clear/unset on this params object.
func (p *ProductUpdateTaxDetailsParams) AddUnsetField(field ProductUpdateTaxDetailsParamsUnsetField) {
	p.UnsetFields = append(p.UnsetFields, field)
}

// Updates the specific product by setting the values of the parameters passed. Any parameters not provided will be left unchanged.
type ProductUpdateParams struct {
	Params `form:"*"`
	// Whether the product is available for purchase.
	Active *bool `form:"active" json:"active,omitempty"`
	// The ID of the [Price](https://docs.stripe.com/api/prices) object that is the default price for this product.
	DefaultPrice *string `form:"default_price" json:"default_price,omitempty"`
	// The product's description, meant to be displayable to the customer. Use this field to optionally store a long form explanation of the product being sold for your own rendering purposes.
	Description *string `form:"description" json:"description,omitempty"`
	// Specifies which fields in the response should be expanded.
	Expand []*string `form:"expand" json:"expand,omitempty"`
	// Other identifiers for this product.
	Identifiers *ProductUpdateIdentifiersParams `form:"identifiers" json:"identifiers,omitempty"`
	// A list of up to 8 URLs of images for this product, meant to be displayable to the customer.
	Images []*string `form:"images" json:"images,omitempty"`
	// A list of up to 15 marketing features for this product. These are displayed in [pricing tables](https://docs.stripe.com/payments/checkout/pricing-table).
	MarketingFeatures []*ProductUpdateMarketingFeatureParams `form:"marketing_features" json:"marketing_features,omitempty"`
	// Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
	Metadata map[string]string `form:"metadata" json:"metadata,omitempty"`
	// The product's name, meant to be displayable to the customer.
	Name *string `form:"name" json:"name,omitempty"`
	// The dimensions of this product for shipping purposes.
	PackageDimensions *ProductUpdatePackageDimensionsParams `form:"package_dimensions" json:"package_dimensions,omitempty"`
	// Whether this product is shipped (i.e., physical goods).
	Shippable *bool `form:"shippable" json:"shippable,omitempty"`
	// An arbitrary string to be displayed on your customer's credit card or bank statement. While most banks display this information consistently, some may display it incorrectly or not at all.
	//
	// This may be up to 22 characters. The statement description may not include `<`, `>`, `\`, `"`, `'` characters, and will appear on your customer's statement in capital letters. Non-ASCII characters are automatically stripped.
	//  It must contain at least one letter. May only be set if `type=service`. Only used for subscription payments.
	StatementDescriptor *string `form:"statement_descriptor" json:"statement_descriptor,omitempty"`
	// A [tax code](https://docs.stripe.com/tax/tax-categories) ID.
	TaxCode *string `form:"tax_code" json:"tax_code,omitempty"`
	// Tax details for this product, including the [tax code](https://docs.stripe.com/tax/tax-codes) and an optional performance location.
	TaxDetails *ProductUpdateTaxDetailsParams `form:"tax_details" json:"tax_details,omitempty"`
	// A label that represents units of this product. When set, this will be included in customers' receipts, invoices, Checkout, and the customer portal. May only be set if `type=service`.
	UnitLabel *string `form:"unit_label" json:"unit_label,omitempty"`
	// A URL of a publicly-accessible webpage for this product.
	URL         *string                         `form:"url" json:"url,omitempty"`
	UnsetFields []ProductUpdateParamsUnsetField `form:"-" json:"-"`
}

// ProductUpdateParamsUnsetField is the list of fields that can be cleared/unset on ProductUpdateParams.
type ProductUpdateParamsUnsetField string

const (
	ProductUpdateParamsUnsetFieldDescription       ProductUpdateParamsUnsetField = "description"
	ProductUpdateParamsUnsetFieldImages            ProductUpdateParamsUnsetField = "images"
	ProductUpdateParamsUnsetFieldMarketingFeatures ProductUpdateParamsUnsetField = "marketing_features"
	ProductUpdateParamsUnsetFieldMetadata          ProductUpdateParamsUnsetField = "metadata"
	ProductUpdateParamsUnsetFieldPackageDimensions ProductUpdateParamsUnsetField = "package_dimensions"
	ProductUpdateParamsUnsetFieldTaxCode           ProductUpdateParamsUnsetField = "tax_code"
	ProductUpdateParamsUnsetFieldTaxDetails        ProductUpdateParamsUnsetField = "tax_details"
	ProductUpdateParamsUnsetFieldUnitLabel         ProductUpdateParamsUnsetField = "unit_label"
	ProductUpdateParamsUnsetFieldURL               ProductUpdateParamsUnsetField = "url"
)

// AddUnsetField adds a field to the list of fields to clear/unset on this params object.
func (p *ProductUpdateParams) AddUnsetField(field ProductUpdateParamsUnsetField) {
	p.UnsetFields = append(p.UnsetFields, field)
}

// AddExpand appends a new field to expand.
func (p *ProductUpdateParams) AddExpand(f string) {
	p.Expand = append(p.Expand, &f)
}

// AddMetadata adds a new key-value pair to the Metadata.
func (p *ProductUpdateParams) AddMetadata(key string, value string) {
	if p.Metadata == nil {
		p.Metadata = make(map[string]string)
	}

	p.Metadata[key] = value
}

// When set, provides configuration for the amount to be adjusted by the customer during Checkout Sessions and Payment Links.
type ProductCreateDefaultPriceDataCurrencyOptionsCustomUnitAmountParams struct {
	// Pass in `true` to enable `custom_unit_amount`, otherwise omit `custom_unit_amount`.
	Enabled *bool `form:"enabled" json:"enabled"`
	// The maximum unit amount the customer can specify for this item.
	Maximum *int64 `form:"maximum" json:"maximum,omitempty"`
	// The minimum unit amount the customer can specify for this item. Must be at least the minimum charge amount.
	Minimum *int64 `form:"minimum" json:"minimum,omitempty"`
	// The starting unit amount which can be updated by the customer.
	Preset *int64 `form:"preset" json:"preset,omitempty"`
}

// Each element represents a pricing tier. This parameter requires `billing_scheme` to be set to `tiered`. See also the documentation for `billing_scheme`.
type ProductCreateDefaultPriceDataCurrencyOptionsTierParams struct {
	// The flat billing amount for an entire tier, regardless of the number of units in the tier.
	FlatAmount *int64 `form:"flat_amount" json:"flat_amount,omitempty"`
	// Same as `flat_amount`, but accepts a decimal value representing an integer in the minor units of the currency. Only one of `flat_amount` and `flat_amount_decimal` can be set.
	FlatAmountDecimal *float64 `form:"flat_amount_decimal,high_precision" json:"flat_amount_decimal,string,omitempty"`
	// The per unit billing amount for each individual unit for which this tier applies.
	UnitAmount *int64 `form:"unit_amount" json:"unit_amount,omitempty"`
	// Same as `unit_amount`, but accepts a decimal value in cents (or local equivalent) with at most 12 decimal places. Only one of `unit_amount` and `unit_amount_decimal` can be set.
	UnitAmountDecimal *float64 `form:"unit_amount_decimal,high_precision" json:"unit_amount_decimal,string,omitempty"`
	// Specifies the upper bound of this tier. The lower bound of a tier is the upper bound of the previous tier adding one. Use `inf` to define a fallback tier.
	UpTo    *int64 `form:"up_to" json:"up_to"`
	UpToInf *bool  `form:"-"` // See custom AppendTo
}

// AppendTo implements custom encoding logic for ProductCreateDefaultPriceDataCurrencyOptionsTierParams.
func (p *ProductCreateDefaultPriceDataCurrencyOptionsTierParams) AppendTo(body *form.Values, keyParts []string) {
	if BoolValue(p.UpToInf) {
		body.Add(form.FormatKey(append(keyParts, "up_to")), "inf")
	}
}

// Prices defined in each available currency option. Each key must be a three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html) and a [supported currency](https://stripe.com/docs/currencies).
type ProductCreateDefaultPriceDataCurrencyOptionsParams struct {
	// When set, provides configuration for the amount to be adjusted by the customer during Checkout Sessions and Payment Links.
	CustomUnitAmount *ProductCreateDefaultPriceDataCurrencyOptionsCustomUnitAmountParams `form:"custom_unit_amount" json:"custom_unit_amount,omitempty"`
	// Only required if a [default tax behavior](https://docs.stripe.com/tax/products-prices-tax-categories-tax-behavior#setting-a-default-tax-behavior-(recommended)) was not provided in the Stripe Tax settings. Specifies whether the price is considered inclusive of taxes or exclusive of taxes. One of `inclusive`, `exclusive`, or `unspecified`. Once specified as either `inclusive` or `exclusive`, it cannot be changed.
	TaxBehavior *string `form:"tax_behavior" json:"tax_behavior,omitempty"`
	// Each element represents a pricing tier. This parameter requires `billing_scheme` to be set to `tiered`. See also the documentation for `billing_scheme`.
	Tiers []*ProductCreateDefaultPriceDataCurrencyOptionsTierParams `form:"tiers" json:"tiers,omitempty"`
	// A positive integer in cents (or local equivalent) (or 0 for a free price) representing how much to charge.
	UnitAmount *int64 `form:"unit_amount" json:"unit_amount,omitempty"`
	// Same as `unit_amount`, but accepts a decimal value in cents (or local equivalent) with at most 12 decimal places. Only one of `unit_amount` and `unit_amount_decimal` can be set.
	UnitAmountDecimal *float64 `form:"unit_amount_decimal,high_precision" json:"unit_amount_decimal,string,omitempty"`
}

// When set, provides configuration for the amount to be adjusted by the customer during Checkout Sessions and Payment Links.
type ProductCreateDefaultPriceDataCustomUnitAmountParams struct {
	// Pass in `true` to enable `custom_unit_amount`, otherwise omit `custom_unit_amount`.
	Enabled *bool `form:"enabled" json:"enabled"`
	// The maximum unit amount the customer can specify for this item.
	Maximum *int64 `form:"maximum" json:"maximum,omitempty"`
	// The minimum unit amount the customer can specify for this item. Must be at least the minimum charge amount.
	Minimum *int64 `form:"minimum" json:"minimum,omitempty"`
	// The starting unit amount which can be updated by the customer.
	Preset *int64 `form:"preset" json:"preset,omitempty"`
}

// The recurring components of a price such as `interval` and `interval_count`.
type ProductCreateDefaultPriceDataRecurringParams struct {
	// Specifies billing frequency. Either `day`, `week`, `month` or `year`.
	Interval *string `form:"interval" json:"interval"`
	// The number of intervals between subscription billings. For example, `interval=month` and `interval_count=3` bills every 3 months. Maximum of three years interval allowed (3 years, 36 months, or 156 weeks).
	IntervalCount *int64 `form:"interval_count" json:"interval_count,omitempty"`
}

// Data used to generate a new [Price](https://docs.stripe.com/api/prices) object. This Price will be set as the default price for this product.
type ProductCreateDefaultPriceDataParams struct {
	// Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
	Currency *string `form:"currency" json:"currency"`
	// Prices defined in each available currency option. Each key must be a three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html) and a [supported currency](https://stripe.com/docs/currencies).
	CurrencyOptions map[string]*ProductCreateDefaultPriceDataCurrencyOptionsParams `form:"currency_options" json:"currency_options,omitempty"`
	// When set, provides configuration for the amount to be adjusted by the customer during Checkout Sessions and Payment Links.
	CustomUnitAmount *ProductCreateDefaultPriceDataCustomUnitAmountParams `form:"custom_unit_amount" json:"custom_unit_amount,omitempty"`
	// Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
	Metadata map[string]string `form:"metadata" json:"metadata,omitempty"`
	// The recurring components of a price such as `interval` and `interval_count`.
	Recurring *ProductCreateDefaultPriceDataRecurringParams `form:"recurring" json:"recurring,omitempty"`
	// Only required if a [default tax behavior](https://docs.stripe.com/tax/products-prices-tax-categories-tax-behavior#setting-a-default-tax-behavior-(recommended)) was not provided in the Stripe Tax settings. Specifies whether the price is considered inclusive of taxes or exclusive of taxes. One of `inclusive`, `exclusive`, or `unspecified`. Once specified as either `inclusive` or `exclusive`, it cannot be changed.
	TaxBehavior *string `form:"tax_behavior" json:"tax_behavior,omitempty"`
	// A positive integer in cents (or local equivalent) (or 0 for a free price) representing how much to charge. One of `unit_amount`, `unit_amount_decimal`, or `custom_unit_amount` is required.
	UnitAmount *int64 `form:"unit_amount" json:"unit_amount,omitempty"`
	// Same as `unit_amount`, but accepts a decimal value in cents (or local equivalent) with at most 12 decimal places. Only one of `unit_amount` and `unit_amount_decimal` can be set.
	UnitAmountDecimal *float64 `form:"unit_amount_decimal,high_precision" json:"unit_amount_decimal,string,omitempty"`
}

// AddMetadata adds a new key-value pair to the Metadata.
func (p *ProductCreateDefaultPriceDataParams) AddMetadata(key string, value string) {
	if p.Metadata == nil {
		p.Metadata = make(map[string]string)
	}

	p.Metadata[key] = value
}

// Other identifiers for this product.
type ProductCreateIdentifiersParams struct {
	// European Article Number (EAN) consisting of 8 or 13 digits and optional dashes. You may optionally provide a leading 0 for a total of 14 digits. The final digit is a validated check digit.
	Ean *string `form:"ean" json:"ean,omitempty"`
	// Global Trade Item Number (GTIN) consisting of 8, 12, 13, or 14 digits and optional dashes. The final digit is a validated check digit.
	Gtin *string `form:"gtin" json:"gtin,omitempty"`
	// International Standard Book Number (ISBN) consisting of 10 or 13 digits and optional dashes. The final digit is a validated check digit. For ISBN-10, the final digit may be a `X`.
	Isbn *string `form:"isbn" json:"isbn,omitempty"`
	// Japanese Article Number (JAN) consisting of 13 digits and optional dashes. The first two digits must either be `45` or `49`. The final digit is a validated check digit.
	Jan *string `form:"jan" json:"jan,omitempty"`
	// Manufacturer Part Number (MPN). May include up to 70 alphanumeric characters and dashes.
	Mpn *string `form:"mpn" json:"mpn,omitempty"`
	// National Stock Number (NSN) consisting of 13 digits and optional dashes. The seventh character may also be alphanumeric.
	Nsn *string `form:"nsn" json:"nsn,omitempty"`
	// Universal Product Code (UPC) consisting of 12 digits and optional dashes. The final digit is a validated check digit.
	Upc *string `form:"upc" json:"upc,omitempty"`
}

// A list of up to 15 marketing features for this product. These are displayed in [pricing tables](https://docs.stripe.com/payments/checkout/pricing-table).
type ProductCreateMarketingFeatureParams struct {
	// The marketing feature name. Up to 80 characters long.
	Name *string `form:"name" json:"name"`
}

// The dimensions of this product for shipping purposes.
type ProductCreatePackageDimensionsParams struct {
	// Height, in inches. Maximum precision is 2 decimal places.
	Height *float64 `form:"height" json:"height"`
	// Length, in inches. Maximum precision is 2 decimal places.
	Length *float64 `form:"length" json:"length"`
	// Weight, in ounces. Maximum precision is 2 decimal places.
	Weight *float64 `form:"weight" json:"weight"`
	// Width, in inches. Maximum precision is 2 decimal places.
	Width *float64 `form:"width" json:"width"`
}

// Tax details for this product, including the [tax code](https://docs.stripe.com/tax/tax-codes) and an optional performance location.
type ProductCreateTaxDetailsParams struct {
	// A tax location ID. Depending on the [tax code](https://docs.stripe.com/tax/tax-for-tickets/reference/tax-location-performance), this is required, optional, or not supported.
	PerformanceLocation *string `form:"performance_location" json:"performance_location,omitempty"`
	// A [tax code](https://docs.stripe.com/tax/tax-categories) ID.
	TaxCode     *string                                   `form:"tax_code" json:"tax_code,omitempty"`
	UnsetFields []ProductCreateTaxDetailsParamsUnsetField `form:"-" json:"-"`
}

// ProductCreateTaxDetailsParamsUnsetField is the list of fields that can be cleared/unset on ProductCreateTaxDetailsParams.
type ProductCreateTaxDetailsParamsUnsetField string

const (
	ProductCreateTaxDetailsParamsUnsetFieldTaxCode ProductCreateTaxDetailsParamsUnsetField = "tax_code"
)

// AddUnsetField adds a field to the list of fields to clear/unset on this params object.
func (p *ProductCreateTaxDetailsParams) AddUnsetField(field ProductCreateTaxDetailsParamsUnsetField) {
	p.UnsetFields = append(p.UnsetFields, field)
}

// Creates a new product object.
type ProductCreateParams struct {
	Params `form:"*"`
	// Whether the product is currently available for purchase. Defaults to `true`.
	Active *bool `form:"active" json:"active,omitempty"`
	// Data used to generate a new [Price](https://docs.stripe.com/api/prices) object. This Price will be set as the default price for this product.
	DefaultPriceData *ProductCreateDefaultPriceDataParams `form:"default_price_data" json:"default_price_data,omitempty"`
	// The product's description, meant to be displayable to the customer. Use this field to optionally store a long form explanation of the product being sold for your own rendering purposes.
	Description *string `form:"description" json:"description,omitempty"`
	// Specifies which fields in the response should be expanded.
	Expand []*string `form:"expand" json:"expand,omitempty"`
	// An identifier will be randomly generated by Stripe. You can optionally override this ID, but the ID must be unique across all products in your Stripe account.
	ID *string `form:"id" json:"id,omitempty"`
	// Other identifiers for this product.
	Identifiers *ProductCreateIdentifiersParams `form:"identifiers" json:"identifiers,omitempty"`
	// A list of up to 8 URLs of images for this product, meant to be displayable to the customer.
	Images []*string `form:"images" json:"images,omitempty"`
	// A list of up to 15 marketing features for this product. These are displayed in [pricing tables](https://docs.stripe.com/payments/checkout/pricing-table).
	MarketingFeatures []*ProductCreateMarketingFeatureParams `form:"marketing_features" json:"marketing_features,omitempty"`
	// Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
	Metadata map[string]string `form:"metadata" json:"metadata,omitempty"`
	// The product's name, meant to be displayable to the customer.
	Name *string `form:"name" json:"name"`
	// The dimensions of this product for shipping purposes.
	PackageDimensions *ProductCreatePackageDimensionsParams `form:"package_dimensions" json:"package_dimensions,omitempty"`
	// Whether this product is shipped (i.e., physical goods).
	Shippable *bool `form:"shippable" json:"shippable,omitempty"`
	// An arbitrary string to be displayed on your customer's credit card or bank statement. While most banks display this information consistently, some may display it incorrectly or not at all.
	//
	// This may be up to 22 characters. The statement description may not include `<`, `>`, `\`, `"`, `'` characters, and will appear on your customer's statement in capital letters. Non-ASCII characters are automatically stripped.
	//  It must contain at least one letter. Only used for subscription payments.
	StatementDescriptor *string `form:"statement_descriptor" json:"statement_descriptor,omitempty"`
	// A [tax code](https://docs.stripe.com/tax/tax-categories) ID.
	TaxCode *string `form:"tax_code" json:"tax_code,omitempty"`
	// Tax details for this product, including the [tax code](https://docs.stripe.com/tax/tax-codes) and an optional performance location.
	TaxDetails *ProductCreateTaxDetailsParams `form:"tax_details" json:"tax_details,omitempty"`
	// The type of the product. Defaults to `service` if not explicitly specified, enabling use of this product with Subscriptions and Plans. Set this parameter to `good` to use this product with Orders and SKUs. On API versions before `2018-02-05`, this field defaults to `good` for compatibility reasons.
	Type *string `form:"type" json:"type,omitempty"`
	// A label that represents units of this product. When set, this will be included in customers' receipts, invoices, Checkout, and the customer portal.
	UnitLabel *string `form:"unit_label" json:"unit_label,omitempty"`
	// A URL of a publicly-accessible webpage for this product.
	URL *string `form:"url" json:"url,omitempty"`
}

// AddExpand appends a new field to expand.
func (p *ProductCreateParams) AddExpand(f string) {
	p.Expand = append(p.Expand, &f)
}

// AddMetadata adds a new key-value pair to the Metadata.
func (p *ProductCreateParams) AddMetadata(key string, value string) {
	if p.Metadata == nil {
		p.Metadata = make(map[string]string)
	}

	p.Metadata[key] = value
}

type ProductIdentifiers struct {
	// European Article Number (EAN) consisting of 8 or 13 digits and optional dashes. You may optionally provide a leading 0 for a total of 14 digits. The final digit is a validated check digit.
	Ean string `json:"ean,omitempty"`
	// Global Trade Item Number (GTIN) consisting of 8, 12, 13, or 14 digits and optional dashes. The final digit is a validated check digit.
	Gtin string `json:"gtin,omitempty"`
	// International Standard Book Number (ISBN) consisting of 10 or 13 digits and optional dashes. The final digit is a validated check digit. For ISBN-10, the final digit may be a `X`.
	Isbn string `json:"isbn,omitempty"`
	// Japanese Article Number (JAN) consisting of 13 digits and optional dashes. The first two digits must either be `45` or `49`. The final digit is a validated check digit.
	Jan string `json:"jan,omitempty"`
	// Manufacturer Part Number (MPN). May include up to 70 alphanumeric characters and dashes.
	Mpn string `json:"mpn,omitempty"`
	// National Stock Number (NSN) consisting of 13 digits and optional dashes. The seventh character may also be alphanumeric.
	Nsn string `json:"nsn,omitempty"`
	// Universal Product Code (UPC) consisting of 12 digits and optional dashes. The final digit is a validated check digit.
	Upc string `json:"upc,omitempty"`
}

// A list of up to 15 marketing features for this product. These are displayed in [pricing tables](https://docs.stripe.com/payments/checkout/pricing-table).
type ProductMarketingFeature struct {
	// The marketing feature name. Up to 80 characters long.
	Name string `json:"name,omitempty"`
}

// The dimensions of this product for shipping purposes.
type ProductPackageDimensions struct {
	// Height, in inches.
	Height float64 `json:"height"`
	// Length, in inches.
	Length float64 `json:"length"`
	// Weight, in ounces.
	Weight float64 `json:"weight"`
	// Width, in inches.
	Width float64 `json:"width"`
}

// Products describe the specific goods or services you offer to your customers.
// For example, you might offer a Standard and Premium version of your goods or service; each version would be a separate Product.
// They can be used in conjunction with [Prices](https://api.stripe.com#prices) to configure pricing in Payment Links, Checkout, and Subscriptions.
//
// Related guides: [Set up a subscription](https://docs.stripe.com/billing/subscriptions/set-up-subscription),
// [share a Payment Link](https://docs.stripe.com/payment-links),
// [accept payments with Checkout](https://docs.stripe.com/payments/accept-a-payment#create-product-prices-upfront),
// and more about [Products and Prices](https://docs.stripe.com/products-prices/overview)
type Product struct {
	APIResource
	// Whether the product is currently available for purchase.
	Active bool `json:"active"`
	// Time at which the object was created. Measured in seconds since the Unix epoch.
	Created int64 `json:"created"`
	// The ID of the [Price](https://docs.stripe.com/api/prices) object that is the default price for this product.
	DefaultPrice *Price `json:"default_price,omitempty"`
	Deleted      bool   `json:"deleted,omitempty"`
	// The product's description, meant to be displayable to the customer. Use this field to optionally store a long form explanation of the product being sold for your own rendering purposes.
	Description string `json:"description"`
	// Unique identifier for the object.
	ID          string              `json:"id"`
	Identifiers *ProductIdentifiers `json:"identifiers,omitempty"`
	// A list of up to 8 URLs of images for this product, meant to be displayable to the customer.
	Images []string `json:"images"`
	// If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
	Livemode bool `json:"livemode"`
	// A list of up to 15 marketing features for this product. These are displayed in [pricing tables](https://docs.stripe.com/payments/checkout/pricing-table).
	MarketingFeatures []*ProductMarketingFeature `json:"marketing_features"`
	// Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
	Metadata map[string]string `json:"metadata"`
	// The product's name, meant to be displayable to the customer.
	Name string `json:"name"`
	// String representing the object's type. Objects of the same type share the same value.
	Object string `json:"object"`
	// The dimensions of this product for shipping purposes.
	PackageDimensions *ProductPackageDimensions `json:"package_dimensions"`
	// Whether this product is shipped (i.e., physical goods).
	Shippable bool `json:"shippable"`
	// Extra information about a product which will appear on your customer's credit card statement. In the case that multiple products are billed at once, the first statement descriptor will be used. Only used for subscription payments.
	StatementDescriptor string `json:"statement_descriptor,omitempty"`
	// A [tax code](https://docs.stripe.com/tax/tax-categories) ID.
	TaxCode *TaxCode `json:"tax_code,omitempty"`
	// The type of the product. The product is either of type `good`, which is eligible for use with Orders and SKUs, or `service`, which is eligible for use with Subscriptions and Plans.
	Type ProductType `json:"type"`
	// A label that represents units of this product. When set, this will be included in customers' receipts, invoices, Checkout, and the customer portal.
	UnitLabel string `json:"unit_label,omitempty"`
	// Time at which the object was last updated. Measured in seconds since the Unix epoch.
	Updated int64 `json:"updated"`
	// A URL of a publicly-accessible webpage for this product.
	URL string `json:"url"`
}

// ProductList is a list of Products as retrieved from a list endpoint.
type ProductList struct {
	APIResource
	ListMeta
	Data []*Product `json:"data"`
}

// ProductSearchResult is a list of Product search results as retrieved from a search endpoint.
type ProductSearchResult struct {
	APIResource
	SearchMeta
	Data []*Product `json:"data"`
}

// UnmarshalJSON handles deserialization of a Product.
// This custom unmarshaling is needed because the resulting
// property may be an id or the full struct if it was expanded.
func (p *Product) UnmarshalJSON(data []byte) error {
	if id, ok := ParseID(data); ok {
		p.ID = id
		return nil
	}

	type product Product
	var v product
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}

	*p = Product(v)
	return nil
}
