//
//
// File generated from our OpenAPI spec
//
//

package stripe

import (
	"context"
	"net/http"

	"github.com/stripe/stripe-go/v82/form"
)

// v1QuotePreviewSubscriptionScheduleService is used to invoke /v1/quotes/{quote}/preview_subscription_schedules APIs.
type v1QuotePreviewSubscriptionScheduleService struct {
	B   Backend
	Key string
}

// Preview the schedules that would be generated by accepting the quote
func (c v1QuotePreviewSubscriptionScheduleService) List(ctx context.Context, listParams *QuotePreviewSubscriptionScheduleListParams) Seq2[*QuotePreviewSubscriptionSchedule, error] {
	if listParams == nil {
		listParams = &QuotePreviewSubscriptionScheduleListParams{}
	}
	listParams.Context = ctx
	path := FormatURLPath(
		"/v1/quotes/%s/preview_subscription_schedules", StringValue(
			listParams.Quote))
	return newV1List(listParams, func(p *Params, b *form.Values) ([]*QuotePreviewSubscriptionSchedule, ListContainer, error) {
		list := &QuotePreviewSubscriptionScheduleList{}
		if p == nil {
			p = &Params{}
		}
		p.Context = ctx
		err := c.B.CallRaw(http.MethodGet, path, c.Key, []byte(b.Encode()), p, list)
		return list.Data, list, err
	}).All()
}
