//
//
// File generated from our OpenAPI spec
//
//

package stripe

import "time"

// Open Enum. Two-letter country code that represents the country where the LegalEntity associated with the FinancialAccount is based in.
type V2MoneyManagementFinancialAccountCountry string

// List of values that V2MoneyManagementFinancialAccountCountry can take
const (
	V2MoneyManagementFinancialAccountCountryAd V2MoneyManagementFinancialAccountCountry = "ad"
	V2MoneyManagementFinancialAccountCountryAe V2MoneyManagementFinancialAccountCountry = "ae"
	V2MoneyManagementFinancialAccountCountryAf V2MoneyManagementFinancialAccountCountry = "af"
	V2MoneyManagementFinancialAccountCountryAg V2MoneyManagementFinancialAccountCountry = "ag"
	V2MoneyManagementFinancialAccountCountryAi V2MoneyManagementFinancialAccountCountry = "ai"
	V2MoneyManagementFinancialAccountCountryAl V2MoneyManagementFinancialAccountCountry = "al"
	V2MoneyManagementFinancialAccountCountryAm V2MoneyManagementFinancialAccountCountry = "am"
	V2MoneyManagementFinancialAccountCountryAo V2MoneyManagementFinancialAccountCountry = "ao"
	V2MoneyManagementFinancialAccountCountryAq V2MoneyManagementFinancialAccountCountry = "aq"
	V2MoneyManagementFinancialAccountCountryAR V2MoneyManagementFinancialAccountCountry = "ar"
	V2MoneyManagementFinancialAccountCountryAs V2MoneyManagementFinancialAccountCountry = "as"
	V2MoneyManagementFinancialAccountCountryAt V2MoneyManagementFinancialAccountCountry = "at"
	V2MoneyManagementFinancialAccountCountryAu V2MoneyManagementFinancialAccountCountry = "au"
	V2MoneyManagementFinancialAccountCountryAw V2MoneyManagementFinancialAccountCountry = "aw"
	V2MoneyManagementFinancialAccountCountryAx V2MoneyManagementFinancialAccountCountry = "ax"
	V2MoneyManagementFinancialAccountCountryAz V2MoneyManagementFinancialAccountCountry = "az"
	V2MoneyManagementFinancialAccountCountryBa V2MoneyManagementFinancialAccountCountry = "ba"
	V2MoneyManagementFinancialAccountCountryBb V2MoneyManagementFinancialAccountCountry = "bb"
	V2MoneyManagementFinancialAccountCountryBd V2MoneyManagementFinancialAccountCountry = "bd"
	V2MoneyManagementFinancialAccountCountryBe V2MoneyManagementFinancialAccountCountry = "be"
	V2MoneyManagementFinancialAccountCountryBf V2MoneyManagementFinancialAccountCountry = "bf"
	V2MoneyManagementFinancialAccountCountryBG V2MoneyManagementFinancialAccountCountry = "bg"
	V2MoneyManagementFinancialAccountCountryBh V2MoneyManagementFinancialAccountCountry = "bh"
	V2MoneyManagementFinancialAccountCountryBi V2MoneyManagementFinancialAccountCountry = "bi"
	V2MoneyManagementFinancialAccountCountryBj V2MoneyManagementFinancialAccountCountry = "bj"
	V2MoneyManagementFinancialAccountCountryBl V2MoneyManagementFinancialAccountCountry = "bl"
	V2MoneyManagementFinancialAccountCountryBm V2MoneyManagementFinancialAccountCountry = "bm"
	V2MoneyManagementFinancialAccountCountryBn V2MoneyManagementFinancialAccountCountry = "bn"
	V2MoneyManagementFinancialAccountCountryBo V2MoneyManagementFinancialAccountCountry = "bo"
	V2MoneyManagementFinancialAccountCountryBq V2MoneyManagementFinancialAccountCountry = "bq"
	V2MoneyManagementFinancialAccountCountryBr V2MoneyManagementFinancialAccountCountry = "br"
	V2MoneyManagementFinancialAccountCountryBs V2MoneyManagementFinancialAccountCountry = "bs"
	V2MoneyManagementFinancialAccountCountryBt V2MoneyManagementFinancialAccountCountry = "bt"
	V2MoneyManagementFinancialAccountCountryBv V2MoneyManagementFinancialAccountCountry = "bv"
	V2MoneyManagementFinancialAccountCountryBw V2MoneyManagementFinancialAccountCountry = "bw"
	V2MoneyManagementFinancialAccountCountryBy V2MoneyManagementFinancialAccountCountry = "by"
	V2MoneyManagementFinancialAccountCountryBz V2MoneyManagementFinancialAccountCountry = "bz"
	V2MoneyManagementFinancialAccountCountryCa V2MoneyManagementFinancialAccountCountry = "ca"
	V2MoneyManagementFinancialAccountCountryCc V2MoneyManagementFinancialAccountCountry = "cc"
	V2MoneyManagementFinancialAccountCountryCd V2MoneyManagementFinancialAccountCountry = "cd"
	V2MoneyManagementFinancialAccountCountryCf V2MoneyManagementFinancialAccountCountry = "cf"
	V2MoneyManagementFinancialAccountCountryCg V2MoneyManagementFinancialAccountCountry = "cg"
	V2MoneyManagementFinancialAccountCountryCh V2MoneyManagementFinancialAccountCountry = "ch"
	V2MoneyManagementFinancialAccountCountryCi V2MoneyManagementFinancialAccountCountry = "ci"
	V2MoneyManagementFinancialAccountCountryCk V2MoneyManagementFinancialAccountCountry = "ck"
	V2MoneyManagementFinancialAccountCountryCl V2MoneyManagementFinancialAccountCountry = "cl"
	V2MoneyManagementFinancialAccountCountryCm V2MoneyManagementFinancialAccountCountry = "cm"
	V2MoneyManagementFinancialAccountCountryCn V2MoneyManagementFinancialAccountCountry = "cn"
	V2MoneyManagementFinancialAccountCountryCo V2MoneyManagementFinancialAccountCountry = "co"
	V2MoneyManagementFinancialAccountCountryCr V2MoneyManagementFinancialAccountCountry = "cr"
	V2MoneyManagementFinancialAccountCountryCu V2MoneyManagementFinancialAccountCountry = "cu"
	V2MoneyManagementFinancialAccountCountryCv V2MoneyManagementFinancialAccountCountry = "cv"
	V2MoneyManagementFinancialAccountCountryCw V2MoneyManagementFinancialAccountCountry = "cw"
	V2MoneyManagementFinancialAccountCountryCx V2MoneyManagementFinancialAccountCountry = "cx"
	V2MoneyManagementFinancialAccountCountryCy V2MoneyManagementFinancialAccountCountry = "cy"
	V2MoneyManagementFinancialAccountCountryCz V2MoneyManagementFinancialAccountCountry = "cz"
	V2MoneyManagementFinancialAccountCountryDE V2MoneyManagementFinancialAccountCountry = "de"
	V2MoneyManagementFinancialAccountCountryDj V2MoneyManagementFinancialAccountCountry = "dj"
	V2MoneyManagementFinancialAccountCountryDk V2MoneyManagementFinancialAccountCountry = "dk"
	V2MoneyManagementFinancialAccountCountryDm V2MoneyManagementFinancialAccountCountry = "dm"
	V2MoneyManagementFinancialAccountCountryDo V2MoneyManagementFinancialAccountCountry = "do"
	V2MoneyManagementFinancialAccountCountryDz V2MoneyManagementFinancialAccountCountry = "dz"
	V2MoneyManagementFinancialAccountCountryEc V2MoneyManagementFinancialAccountCountry = "ec"
	V2MoneyManagementFinancialAccountCountryEe V2MoneyManagementFinancialAccountCountry = "ee"
	V2MoneyManagementFinancialAccountCountryEg V2MoneyManagementFinancialAccountCountry = "eg"
	V2MoneyManagementFinancialAccountCountryEh V2MoneyManagementFinancialAccountCountry = "eh"
	V2MoneyManagementFinancialAccountCountryEr V2MoneyManagementFinancialAccountCountry = "er"
	V2MoneyManagementFinancialAccountCountryES V2MoneyManagementFinancialAccountCountry = "es"
	V2MoneyManagementFinancialAccountCountryET V2MoneyManagementFinancialAccountCountry = "et"
	V2MoneyManagementFinancialAccountCountryFI V2MoneyManagementFinancialAccountCountry = "fi"
	V2MoneyManagementFinancialAccountCountryFj V2MoneyManagementFinancialAccountCountry = "fj"
	V2MoneyManagementFinancialAccountCountryFk V2MoneyManagementFinancialAccountCountry = "fk"
	V2MoneyManagementFinancialAccountCountryFm V2MoneyManagementFinancialAccountCountry = "fm"
	V2MoneyManagementFinancialAccountCountryFo V2MoneyManagementFinancialAccountCountry = "fo"
	V2MoneyManagementFinancialAccountCountryFR V2MoneyManagementFinancialAccountCountry = "fr"
	V2MoneyManagementFinancialAccountCountryGa V2MoneyManagementFinancialAccountCountry = "ga"
	V2MoneyManagementFinancialAccountCountryGB V2MoneyManagementFinancialAccountCountry = "gb"
	V2MoneyManagementFinancialAccountCountryGd V2MoneyManagementFinancialAccountCountry = "gd"
	V2MoneyManagementFinancialAccountCountryGe V2MoneyManagementFinancialAccountCountry = "ge"
	V2MoneyManagementFinancialAccountCountryGf V2MoneyManagementFinancialAccountCountry = "gf"
	V2MoneyManagementFinancialAccountCountryGg V2MoneyManagementFinancialAccountCountry = "gg"
	V2MoneyManagementFinancialAccountCountryGh V2MoneyManagementFinancialAccountCountry = "gh"
	V2MoneyManagementFinancialAccountCountryGi V2MoneyManagementFinancialAccountCountry = "gi"
	V2MoneyManagementFinancialAccountCountryGl V2MoneyManagementFinancialAccountCountry = "gl"
	V2MoneyManagementFinancialAccountCountryGm V2MoneyManagementFinancialAccountCountry = "gm"
	V2MoneyManagementFinancialAccountCountryGn V2MoneyManagementFinancialAccountCountry = "gn"
	V2MoneyManagementFinancialAccountCountryGp V2MoneyManagementFinancialAccountCountry = "gp"
	V2MoneyManagementFinancialAccountCountryGq V2MoneyManagementFinancialAccountCountry = "gq"
	V2MoneyManagementFinancialAccountCountryGr V2MoneyManagementFinancialAccountCountry = "gr"
	V2MoneyManagementFinancialAccountCountryGs V2MoneyManagementFinancialAccountCountry = "gs"
	V2MoneyManagementFinancialAccountCountryGt V2MoneyManagementFinancialAccountCountry = "gt"
	V2MoneyManagementFinancialAccountCountryGu V2MoneyManagementFinancialAccountCountry = "gu"
	V2MoneyManagementFinancialAccountCountryGw V2MoneyManagementFinancialAccountCountry = "gw"
	V2MoneyManagementFinancialAccountCountryGy V2MoneyManagementFinancialAccountCountry = "gy"
	V2MoneyManagementFinancialAccountCountryHk V2MoneyManagementFinancialAccountCountry = "hk"
	V2MoneyManagementFinancialAccountCountryHm V2MoneyManagementFinancialAccountCountry = "hm"
	V2MoneyManagementFinancialAccountCountryHn V2MoneyManagementFinancialAccountCountry = "hn"
	V2MoneyManagementFinancialAccountCountryHR V2MoneyManagementFinancialAccountCountry = "hr"
	V2MoneyManagementFinancialAccountCountryHt V2MoneyManagementFinancialAccountCountry = "ht"
	V2MoneyManagementFinancialAccountCountryHU V2MoneyManagementFinancialAccountCountry = "hu"
	V2MoneyManagementFinancialAccountCountryID V2MoneyManagementFinancialAccountCountry = "id"
	V2MoneyManagementFinancialAccountCountryIe V2MoneyManagementFinancialAccountCountry = "ie"
	V2MoneyManagementFinancialAccountCountryIl V2MoneyManagementFinancialAccountCountry = "il"
	V2MoneyManagementFinancialAccountCountryIm V2MoneyManagementFinancialAccountCountry = "im"
	V2MoneyManagementFinancialAccountCountryIn V2MoneyManagementFinancialAccountCountry = "in"
	V2MoneyManagementFinancialAccountCountryIo V2MoneyManagementFinancialAccountCountry = "io"
	V2MoneyManagementFinancialAccountCountryIq V2MoneyManagementFinancialAccountCountry = "iq"
	V2MoneyManagementFinancialAccountCountryIr V2MoneyManagementFinancialAccountCountry = "ir"
	V2MoneyManagementFinancialAccountCountryIs V2MoneyManagementFinancialAccountCountry = "is"
	V2MoneyManagementFinancialAccountCountryIT V2MoneyManagementFinancialAccountCountry = "it"
	V2MoneyManagementFinancialAccountCountryJe V2MoneyManagementFinancialAccountCountry = "je"
	V2MoneyManagementFinancialAccountCountryJm V2MoneyManagementFinancialAccountCountry = "jm"
	V2MoneyManagementFinancialAccountCountryJo V2MoneyManagementFinancialAccountCountry = "jo"
	V2MoneyManagementFinancialAccountCountryJP V2MoneyManagementFinancialAccountCountry = "jp"
	V2MoneyManagementFinancialAccountCountryKe V2MoneyManagementFinancialAccountCountry = "ke"
	V2MoneyManagementFinancialAccountCountryKg V2MoneyManagementFinancialAccountCountry = "kg"
	V2MoneyManagementFinancialAccountCountryKh V2MoneyManagementFinancialAccountCountry = "kh"
	V2MoneyManagementFinancialAccountCountryKi V2MoneyManagementFinancialAccountCountry = "ki"
	V2MoneyManagementFinancialAccountCountryKm V2MoneyManagementFinancialAccountCountry = "km"
	V2MoneyManagementFinancialAccountCountryKn V2MoneyManagementFinancialAccountCountry = "kn"
	V2MoneyManagementFinancialAccountCountryKp V2MoneyManagementFinancialAccountCountry = "kp"
	V2MoneyManagementFinancialAccountCountryKr V2MoneyManagementFinancialAccountCountry = "kr"
	V2MoneyManagementFinancialAccountCountryKw V2MoneyManagementFinancialAccountCountry = "kw"
	V2MoneyManagementFinancialAccountCountryKy V2MoneyManagementFinancialAccountCountry = "ky"
	V2MoneyManagementFinancialAccountCountryKz V2MoneyManagementFinancialAccountCountry = "kz"
	V2MoneyManagementFinancialAccountCountryLa V2MoneyManagementFinancialAccountCountry = "la"
	V2MoneyManagementFinancialAccountCountryLb V2MoneyManagementFinancialAccountCountry = "lb"
	V2MoneyManagementFinancialAccountCountryLc V2MoneyManagementFinancialAccountCountry = "lc"
	V2MoneyManagementFinancialAccountCountryLi V2MoneyManagementFinancialAccountCountry = "li"
	V2MoneyManagementFinancialAccountCountryLk V2MoneyManagementFinancialAccountCountry = "lk"
	V2MoneyManagementFinancialAccountCountryLr V2MoneyManagementFinancialAccountCountry = "lr"
	V2MoneyManagementFinancialAccountCountryLs V2MoneyManagementFinancialAccountCountry = "ls"
	V2MoneyManagementFinancialAccountCountryLT V2MoneyManagementFinancialAccountCountry = "lt"
	V2MoneyManagementFinancialAccountCountryLu V2MoneyManagementFinancialAccountCountry = "lu"
	V2MoneyManagementFinancialAccountCountryLV V2MoneyManagementFinancialAccountCountry = "lv"
	V2MoneyManagementFinancialAccountCountryLy V2MoneyManagementFinancialAccountCountry = "ly"
	V2MoneyManagementFinancialAccountCountryMa V2MoneyManagementFinancialAccountCountry = "ma"
	V2MoneyManagementFinancialAccountCountryMc V2MoneyManagementFinancialAccountCountry = "mc"
	V2MoneyManagementFinancialAccountCountryMd V2MoneyManagementFinancialAccountCountry = "md"
	V2MoneyManagementFinancialAccountCountryMe V2MoneyManagementFinancialAccountCountry = "me"
	V2MoneyManagementFinancialAccountCountryMf V2MoneyManagementFinancialAccountCountry = "mf"
	V2MoneyManagementFinancialAccountCountryMg V2MoneyManagementFinancialAccountCountry = "mg"
	V2MoneyManagementFinancialAccountCountryMh V2MoneyManagementFinancialAccountCountry = "mh"
	V2MoneyManagementFinancialAccountCountryMk V2MoneyManagementFinancialAccountCountry = "mk"
	V2MoneyManagementFinancialAccountCountryMl V2MoneyManagementFinancialAccountCountry = "ml"
	V2MoneyManagementFinancialAccountCountryMm V2MoneyManagementFinancialAccountCountry = "mm"
	V2MoneyManagementFinancialAccountCountryMn V2MoneyManagementFinancialAccountCountry = "mn"
	V2MoneyManagementFinancialAccountCountryMo V2MoneyManagementFinancialAccountCountry = "mo"
	V2MoneyManagementFinancialAccountCountryMp V2MoneyManagementFinancialAccountCountry = "mp"
	V2MoneyManagementFinancialAccountCountryMq V2MoneyManagementFinancialAccountCountry = "mq"
	V2MoneyManagementFinancialAccountCountryMr V2MoneyManagementFinancialAccountCountry = "mr"
	V2MoneyManagementFinancialAccountCountryMS V2MoneyManagementFinancialAccountCountry = "ms"
	V2MoneyManagementFinancialAccountCountryMT V2MoneyManagementFinancialAccountCountry = "mt"
	V2MoneyManagementFinancialAccountCountryMu V2MoneyManagementFinancialAccountCountry = "mu"
	V2MoneyManagementFinancialAccountCountryMv V2MoneyManagementFinancialAccountCountry = "mv"
	V2MoneyManagementFinancialAccountCountryMw V2MoneyManagementFinancialAccountCountry = "mw"
	V2MoneyManagementFinancialAccountCountryMX V2MoneyManagementFinancialAccountCountry = "mx"
	V2MoneyManagementFinancialAccountCountryMy V2MoneyManagementFinancialAccountCountry = "my"
	V2MoneyManagementFinancialAccountCountryMz V2MoneyManagementFinancialAccountCountry = "mz"
	V2MoneyManagementFinancialAccountCountryNa V2MoneyManagementFinancialAccountCountry = "na"
	V2MoneyManagementFinancialAccountCountryNc V2MoneyManagementFinancialAccountCountry = "nc"
	V2MoneyManagementFinancialAccountCountryNe V2MoneyManagementFinancialAccountCountry = "ne"
	V2MoneyManagementFinancialAccountCountryNf V2MoneyManagementFinancialAccountCountry = "nf"
	V2MoneyManagementFinancialAccountCountryNg V2MoneyManagementFinancialAccountCountry = "ng"
	V2MoneyManagementFinancialAccountCountryNi V2MoneyManagementFinancialAccountCountry = "ni"
	V2MoneyManagementFinancialAccountCountryNL V2MoneyManagementFinancialAccountCountry = "nl"
	V2MoneyManagementFinancialAccountCountryNo V2MoneyManagementFinancialAccountCountry = "no"
	V2MoneyManagementFinancialAccountCountryNp V2MoneyManagementFinancialAccountCountry = "np"
	V2MoneyManagementFinancialAccountCountryNr V2MoneyManagementFinancialAccountCountry = "nr"
	V2MoneyManagementFinancialAccountCountryNu V2MoneyManagementFinancialAccountCountry = "nu"
	V2MoneyManagementFinancialAccountCountryNz V2MoneyManagementFinancialAccountCountry = "nz"
	V2MoneyManagementFinancialAccountCountryOm V2MoneyManagementFinancialAccountCountry = "om"
	V2MoneyManagementFinancialAccountCountryPa V2MoneyManagementFinancialAccountCountry = "pa"
	V2MoneyManagementFinancialAccountCountryPe V2MoneyManagementFinancialAccountCountry = "pe"
	V2MoneyManagementFinancialAccountCountryPf V2MoneyManagementFinancialAccountCountry = "pf"
	V2MoneyManagementFinancialAccountCountryPg V2MoneyManagementFinancialAccountCountry = "pg"
	V2MoneyManagementFinancialAccountCountryPh V2MoneyManagementFinancialAccountCountry = "ph"
	V2MoneyManagementFinancialAccountCountryPk V2MoneyManagementFinancialAccountCountry = "pk"
	V2MoneyManagementFinancialAccountCountryPL V2MoneyManagementFinancialAccountCountry = "pl"
	V2MoneyManagementFinancialAccountCountryPm V2MoneyManagementFinancialAccountCountry = "pm"
	V2MoneyManagementFinancialAccountCountryPn V2MoneyManagementFinancialAccountCountry = "pn"
	V2MoneyManagementFinancialAccountCountryPr V2MoneyManagementFinancialAccountCountry = "pr"
	V2MoneyManagementFinancialAccountCountryPs V2MoneyManagementFinancialAccountCountry = "ps"
	V2MoneyManagementFinancialAccountCountryPT V2MoneyManagementFinancialAccountCountry = "pt"
	V2MoneyManagementFinancialAccountCountryPw V2MoneyManagementFinancialAccountCountry = "pw"
	V2MoneyManagementFinancialAccountCountryPy V2MoneyManagementFinancialAccountCountry = "py"
	V2MoneyManagementFinancialAccountCountryQa V2MoneyManagementFinancialAccountCountry = "qa"
	V2MoneyManagementFinancialAccountCountryQz V2MoneyManagementFinancialAccountCountry = "qz"
	V2MoneyManagementFinancialAccountCountryRe V2MoneyManagementFinancialAccountCountry = "re"
	V2MoneyManagementFinancialAccountCountryRO V2MoneyManagementFinancialAccountCountry = "ro"
	V2MoneyManagementFinancialAccountCountryRs V2MoneyManagementFinancialAccountCountry = "rs"
	V2MoneyManagementFinancialAccountCountryRU V2MoneyManagementFinancialAccountCountry = "ru"
	V2MoneyManagementFinancialAccountCountryRw V2MoneyManagementFinancialAccountCountry = "rw"
	V2MoneyManagementFinancialAccountCountrySa V2MoneyManagementFinancialAccountCountry = "sa"
	V2MoneyManagementFinancialAccountCountrySb V2MoneyManagementFinancialAccountCountry = "sb"
	V2MoneyManagementFinancialAccountCountrySc V2MoneyManagementFinancialAccountCountry = "sc"
	V2MoneyManagementFinancialAccountCountrySd V2MoneyManagementFinancialAccountCountry = "sd"
	V2MoneyManagementFinancialAccountCountrySe V2MoneyManagementFinancialAccountCountry = "se"
	V2MoneyManagementFinancialAccountCountrySg V2MoneyManagementFinancialAccountCountry = "sg"
	V2MoneyManagementFinancialAccountCountrySh V2MoneyManagementFinancialAccountCountry = "sh"
	V2MoneyManagementFinancialAccountCountrySi V2MoneyManagementFinancialAccountCountry = "si"
	V2MoneyManagementFinancialAccountCountrySj V2MoneyManagementFinancialAccountCountry = "sj"
	V2MoneyManagementFinancialAccountCountrySK V2MoneyManagementFinancialAccountCountry = "sk"
	V2MoneyManagementFinancialAccountCountrySL V2MoneyManagementFinancialAccountCountry = "sl"
	V2MoneyManagementFinancialAccountCountrySm V2MoneyManagementFinancialAccountCountry = "sm"
	V2MoneyManagementFinancialAccountCountrySn V2MoneyManagementFinancialAccountCountry = "sn"
	V2MoneyManagementFinancialAccountCountrySo V2MoneyManagementFinancialAccountCountry = "so"
	V2MoneyManagementFinancialAccountCountrySr V2MoneyManagementFinancialAccountCountry = "sr"
	V2MoneyManagementFinancialAccountCountrySs V2MoneyManagementFinancialAccountCountry = "ss"
	V2MoneyManagementFinancialAccountCountrySt V2MoneyManagementFinancialAccountCountry = "st"
	V2MoneyManagementFinancialAccountCountrySV V2MoneyManagementFinancialAccountCountry = "sv"
	V2MoneyManagementFinancialAccountCountrySx V2MoneyManagementFinancialAccountCountry = "sx"
	V2MoneyManagementFinancialAccountCountrySy V2MoneyManagementFinancialAccountCountry = "sy"
	V2MoneyManagementFinancialAccountCountrySz V2MoneyManagementFinancialAccountCountry = "sz"
	V2MoneyManagementFinancialAccountCountryTc V2MoneyManagementFinancialAccountCountry = "tc"
	V2MoneyManagementFinancialAccountCountryTd V2MoneyManagementFinancialAccountCountry = "td"
	V2MoneyManagementFinancialAccountCountryTf V2MoneyManagementFinancialAccountCountry = "tf"
	V2MoneyManagementFinancialAccountCountryTg V2MoneyManagementFinancialAccountCountry = "tg"
	V2MoneyManagementFinancialAccountCountryTH V2MoneyManagementFinancialAccountCountry = "th"
	V2MoneyManagementFinancialAccountCountryTj V2MoneyManagementFinancialAccountCountry = "tj"
	V2MoneyManagementFinancialAccountCountryTk V2MoneyManagementFinancialAccountCountry = "tk"
	V2MoneyManagementFinancialAccountCountryTl V2MoneyManagementFinancialAccountCountry = "tl"
	V2MoneyManagementFinancialAccountCountryTm V2MoneyManagementFinancialAccountCountry = "tm"
	V2MoneyManagementFinancialAccountCountryTn V2MoneyManagementFinancialAccountCountry = "tn"
	V2MoneyManagementFinancialAccountCountryTo V2MoneyManagementFinancialAccountCountry = "to"
	V2MoneyManagementFinancialAccountCountryTR V2MoneyManagementFinancialAccountCountry = "tr"
	V2MoneyManagementFinancialAccountCountryTt V2MoneyManagementFinancialAccountCountry = "tt"
	V2MoneyManagementFinancialAccountCountryTv V2MoneyManagementFinancialAccountCountry = "tv"
	V2MoneyManagementFinancialAccountCountryTw V2MoneyManagementFinancialAccountCountry = "tw"
	V2MoneyManagementFinancialAccountCountryTz V2MoneyManagementFinancialAccountCountry = "tz"
	V2MoneyManagementFinancialAccountCountryUa V2MoneyManagementFinancialAccountCountry = "ua"
	V2MoneyManagementFinancialAccountCountryUg V2MoneyManagementFinancialAccountCountry = "ug"
	V2MoneyManagementFinancialAccountCountryUm V2MoneyManagementFinancialAccountCountry = "um"
	V2MoneyManagementFinancialAccountCountryUS V2MoneyManagementFinancialAccountCountry = "us"
	V2MoneyManagementFinancialAccountCountryUy V2MoneyManagementFinancialAccountCountry = "uy"
	V2MoneyManagementFinancialAccountCountryUz V2MoneyManagementFinancialAccountCountry = "uz"
	V2MoneyManagementFinancialAccountCountryVa V2MoneyManagementFinancialAccountCountry = "va"
	V2MoneyManagementFinancialAccountCountryVc V2MoneyManagementFinancialAccountCountry = "vc"
	V2MoneyManagementFinancialAccountCountryVe V2MoneyManagementFinancialAccountCountry = "ve"
	V2MoneyManagementFinancialAccountCountryVg V2MoneyManagementFinancialAccountCountry = "vg"
	V2MoneyManagementFinancialAccountCountryVI V2MoneyManagementFinancialAccountCountry = "vi"
	V2MoneyManagementFinancialAccountCountryVn V2MoneyManagementFinancialAccountCountry = "vn"
	V2MoneyManagementFinancialAccountCountryVu V2MoneyManagementFinancialAccountCountry = "vu"
	V2MoneyManagementFinancialAccountCountryWf V2MoneyManagementFinancialAccountCountry = "wf"
	V2MoneyManagementFinancialAccountCountryWs V2MoneyManagementFinancialAccountCountry = "ws"
	V2MoneyManagementFinancialAccountCountryXx V2MoneyManagementFinancialAccountCountry = "xx"
	V2MoneyManagementFinancialAccountCountryYe V2MoneyManagementFinancialAccountCountry = "ye"
	V2MoneyManagementFinancialAccountCountryYt V2MoneyManagementFinancialAccountCountry = "yt"
	V2MoneyManagementFinancialAccountCountryZa V2MoneyManagementFinancialAccountCountry = "za"
	V2MoneyManagementFinancialAccountCountryZm V2MoneyManagementFinancialAccountCountry = "zm"
	V2MoneyManagementFinancialAccountCountryZw V2MoneyManagementFinancialAccountCountry = "zw"
)

// Closed Enum. An enum representing the status of the FinancialAccount. This indicates whether or not the FinancialAccount can be used for any money movement flows.
type V2MoneyManagementFinancialAccountStatus string

// List of values that V2MoneyManagementFinancialAccountStatus can take
const (
	V2MoneyManagementFinancialAccountStatusClosed  V2MoneyManagementFinancialAccountStatus = "closed"
	V2MoneyManagementFinancialAccountStatusOpen    V2MoneyManagementFinancialAccountStatus = "open"
	V2MoneyManagementFinancialAccountStatusPending V2MoneyManagementFinancialAccountStatus = "pending"
)

type V2MoneyManagementFinancialAccountStatusDetailsClosedReason string

// List of values that V2MoneyManagementFinancialAccountStatusDetailsClosedReason can take
const (
	V2MoneyManagementFinancialAccountStatusDetailsClosedReasonAccountClosed    V2MoneyManagementFinancialAccountStatusDetailsClosedReason = "account_closed"
	V2MoneyManagementFinancialAccountStatusDetailsClosedReasonClosedByPlatform V2MoneyManagementFinancialAccountStatusDetailsClosedReason = "closed_by_platform"
	V2MoneyManagementFinancialAccountStatusDetailsClosedReasonOther            V2MoneyManagementFinancialAccountStatusDetailsClosedReason = "other"
)

// The currencies that this FinancialAccount can hold.
type V2MoneyManagementFinancialAccountStorageHoldsCurrency string

// List of values that V2MoneyManagementFinancialAccountStorageHoldsCurrency can take
const (
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyAed  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "aed"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyAfn  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "afn"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyAll  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "all"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyAmd  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "amd"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyAng  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "ang"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyAoa  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "aoa"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyArs  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "ars"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyAUD  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "aud"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyAwg  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "awg"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyAzn  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "azn"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyBam  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "bam"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyBbd  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "bbd"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyBdt  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "bdt"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyBgn  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "bgn"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyBhd  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "bhd"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyBif  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "bif"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyBmd  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "bmd"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyBnd  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "bnd"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyBob  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "bob"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyBov  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "bov"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyBrl  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "brl"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyBsd  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "bsd"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyBtn  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "btn"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyBwp  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "bwp"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyByn  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "byn"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyByr  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "byr"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyBzd  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "bzd"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyCAD  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "cad"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyCdf  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "cdf"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyChe  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "che"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyCHF  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "chf"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyChw  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "chw"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyClf  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "clf"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyClp  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "clp"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyCny  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "cny"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyCop  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "cop"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyCou  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "cou"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyCrc  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "crc"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyCuc  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "cuc"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyCup  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "cup"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyCve  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "cve"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyCZK  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "czk"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyDjf  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "djf"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyDKK  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "dkk"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyDop  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "dop"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyDzd  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "dzd"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyEek  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "eek"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyEgp  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "egp"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyErn  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "ern"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyEtb  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "etb"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyEUR  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "eur"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyFjd  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "fjd"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyFkp  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "fkp"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyGBP  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "gbp"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyGel  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "gel"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyGhc  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "ghc"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyGhs  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "ghs"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyGip  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "gip"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyGmd  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "gmd"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyGnf  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "gnf"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyGtq  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "gtq"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyGyd  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "gyd"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyHKD  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "hkd"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyHnl  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "hnl"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyHrk  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "hrk"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyHtg  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "htg"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyHuf  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "huf"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyIdr  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "idr"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyIls  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "ils"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyInr  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "inr"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyIqd  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "iqd"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyIrr  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "irr"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyIsk  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "isk"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyJmd  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "jmd"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyJod  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "jod"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyJPY  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "jpy"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyKes  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "kes"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyKgs  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "kgs"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyKhr  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "khr"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyKmf  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "kmf"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyKpw  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "kpw"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyKrw  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "krw"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyKwd  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "kwd"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyKyd  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "kyd"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyKzt  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "kzt"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyLak  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "lak"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyLbp  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "lbp"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyLkr  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "lkr"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyLrd  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "lrd"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyLsl  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "lsl"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyLtl  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "ltl"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyLvl  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "lvl"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyLyd  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "lyd"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyMad  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "mad"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyMdl  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "mdl"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyMga  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "mga"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyMkd  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "mkd"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyMmk  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "mmk"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyMnt  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "mnt"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyMop  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "mop"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyMro  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "mro"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyMru  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "mru"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyMur  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "mur"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyMvr  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "mvr"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyMwk  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "mwk"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyMxn  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "mxn"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyMxv  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "mxv"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyMYR  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "myr"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyMzn  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "mzn"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyNad  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "nad"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyNgn  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "ngn"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyNio  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "nio"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyNOK  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "nok"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyNpr  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "npr"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyNZD  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "nzd"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyOmr  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "omr"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyPab  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "pab"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyPen  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "pen"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyPgk  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "pgk"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyPhp  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "php"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyPkr  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "pkr"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyPLN  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "pln"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyPyg  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "pyg"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyQar  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "qar"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyRon  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "ron"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyRsd  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "rsd"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyRub  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "rub"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyRwf  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "rwf"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencySar  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "sar"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencySbd  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "sbd"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyScr  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "scr"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencySdg  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "sdg"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencySEK  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "sek"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencySGD  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "sgd"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyShp  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "shp"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencySle  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "sle"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencySll  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "sll"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencySos  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "sos"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencySrd  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "srd"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencySsp  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "ssp"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyStd  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "std"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyStn  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "stn"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencySvc  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "svc"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencySyp  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "syp"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencySzl  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "szl"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyThb  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "thb"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyTjs  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "tjs"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyTmt  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "tmt"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyTnd  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "tnd"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyTop  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "top"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyTry  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "try"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyTtd  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "ttd"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyTwd  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "twd"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyTzs  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "tzs"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyUah  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "uah"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyUgx  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "ugx"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyUSD  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "usd"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyUsdb V2MoneyManagementFinancialAccountStorageHoldsCurrency = "usdb"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyUsdc V2MoneyManagementFinancialAccountStorageHoldsCurrency = "usdc"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyUsn  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "usn"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyUyi  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "uyi"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyUyu  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "uyu"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyUzs  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "uzs"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyVef  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "vef"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyVes  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "ves"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyVnd  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "vnd"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyVuv  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "vuv"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyWst  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "wst"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyXaf  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "xaf"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyXcd  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "xcd"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyXcg  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "xcg"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyXof  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "xof"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyXpf  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "xpf"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyYer  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "yer"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyZar  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "zar"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyZmk  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "zmk"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyZmw  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "zmw"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyZwd  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "zwd"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyZwg  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "zwg"
	V2MoneyManagementFinancialAccountStorageHoldsCurrencyZwl  V2MoneyManagementFinancialAccountStorageHoldsCurrency = "zwl"
)

// Type of the FinancialAccount. An additional hash is included on the FinancialAccount with a name matching this value.
// It contains additional information specific to the FinancialAccount type.
type V2MoneyManagementFinancialAccountType string

// List of values that V2MoneyManagementFinancialAccountType can take
const (
	V2MoneyManagementFinancialAccountTypeOther   V2MoneyManagementFinancialAccountType = "other"
	V2MoneyManagementFinancialAccountTypeStorage V2MoneyManagementFinancialAccountType = "storage"
)

// Multi-currency balance of this FinancialAccount, split by availability state. Each balance is represented as a hash where the key is the three-letter ISO currency code, in lowercase, and the value is the amount for that currency.
type V2MoneyManagementFinancialAccountBalance struct {
	// Balance that can be used for money movement.
	Available map[string]Amount `json:"available"`
	// Balance of inbound funds that will later transition to the `available` balance.
	InboundPending map[string]Amount `json:"inbound_pending"`
	// Balance of funds that are being used for a pending outbound money movement.
	OutboundPending map[string]Amount `json:"outbound_pending"`
}

// If this is a `other` FinancialAccount, this hash indicates what the actual type is. Upgrade your API version to see it reflected in `type`.
type V2MoneyManagementFinancialAccountOther struct {
	// The type of the FinancialAccount, represented as a string. Upgrade your API version to see the type reflected in `financial_account.type`.
	Type string `json:"type"`
}
type V2MoneyManagementFinancialAccountStatusDetailsClosedForwardingSettings struct {
	// The address to send forwarded payments to.
	PaymentMethod string `json:"payment_method"`
	// The address to send forwarded payouts to.
	PayoutMethod string `json:"payout_method"`
}
type V2MoneyManagementFinancialAccountStatusDetailsClosed struct {
	ForwardingSettings *V2MoneyManagementFinancialAccountStatusDetailsClosedForwardingSettings `json:"forwarding_settings"`
	Reason             V2MoneyManagementFinancialAccountStatusDetailsClosedReason              `json:"reason"`
}
type V2MoneyManagementFinancialAccountStatusDetails struct {
	Closed *V2MoneyManagementFinancialAccountStatusDetailsClosed `json:"closed"`
}

// If this is a `storage` FinancialAccount, this hash includes details specific to `storage` FinancialAccounts.
type V2MoneyManagementFinancialAccountStorage struct {
	// The currencies that this FinancialAccount can hold.
	HoldsCurrencies []V2MoneyManagementFinancialAccountStorageHoldsCurrency `json:"holds_currencies"`
}

// The Financial Account is the container that allows for the configuration of money movement.
type V2MoneyManagementFinancialAccount struct {
	APIResource
	// Multi-currency balance of this FinancialAccount, split by availability state. Each balance is represented as a hash where the key is the three-letter ISO currency code, in lowercase, and the value is the amount for that currency.
	Balance *V2MoneyManagementFinancialAccountBalance `json:"balance"`
	// Open Enum. Two-letter country code that represents the country where the LegalEntity associated with the FinancialAccount is based in.
	Country V2MoneyManagementFinancialAccountCountry `json:"country"`
	// Time at which the object was created.
	Created time.Time `json:"created"`
	// A descriptive name for the FinancialAccount, up to 50 characters long. This name will be used in the Stripe Dashboard and embedded components.
	DisplayName string `json:"display_name"`
	// Unique identifier for the object.
	ID string `json:"id"`
	// Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.
	Livemode bool `json:"livemode"`
	// Metadata associated with the FinancialAccount
	Metadata map[string]string `json:"metadata"`
	// String representing the object's type. Objects of the same type share the same value of the object field.
	Object string `json:"object"`
	// If this is a `other` FinancialAccount, this hash indicates what the actual type is. Upgrade your API version to see it reflected in `type`.
	Other *V2MoneyManagementFinancialAccountOther `json:"other"`
	// Closed Enum. An enum representing the status of the FinancialAccount. This indicates whether or not the FinancialAccount can be used for any money movement flows.
	Status        V2MoneyManagementFinancialAccountStatus         `json:"status"`
	StatusDetails *V2MoneyManagementFinancialAccountStatusDetails `json:"status_details"`
	// If this is a `storage` FinancialAccount, this hash includes details specific to `storage` FinancialAccounts.
	Storage *V2MoneyManagementFinancialAccountStorage `json:"storage"`
	// Type of the FinancialAccount. An additional hash is included on the FinancialAccount with a name matching this value.
	// It contains additional information specific to the FinancialAccount type.
	Type V2MoneyManagementFinancialAccountType `json:"type"`
}
